#
# Sample postfwd docker compose file - http://postfwd.org/docker
#
# combined use of postfwd1 and postfwd2
#
# Edit ruleset/postfwd-complex.cf and use with:
#
#       docker-compose -f docker-compose-complex.yml build --pull
#       docker-compose -f docker-compose-complex.yml up

version: '2' 

services:

  postfwd2:
    image: postfwd/postfwd:stable
    environment:
      # use 'postfwd1' or 'postfwd2' to switch between versions
      - PROG=postfwd2
    restart: always
    ports:
      - 127.0.0.1:10095:10040
    volumes:
      - ./postfwd-rates.cf:/etc/postfwd/postfwd.cf:ro
      - postfwd-data:/var/lib/postfwd

volumes:

  postfwd-data:
    # empty

